spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cfdb
    username: root
    password: 843460950
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8081
mybatis:
  config-location: classpath:mybatis-config.xml